LebPelenFilmow/urls.py
from django.contrib import admin
from django.urls import path, include
from movie import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ListMovieView.as_view(), name='index'),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('singup/', views.SignUpView.as_view(), name='signup'),
]

movie/urls.py
from django.urls import path
from movie import views

urlpatterns = [
    path('', views.AddMovieView.as_view(), name='add_movie'),
    path('list_movie/', views.ListMovieView.as_view(), name='list_movie'),
    path('add_actor/', views.AddActorView.as_view(), name='add_actor'),
    path('list_actor/', views.ListActorView.as_view(), name='list_actor'),
    path('detailActorView/<int:pk>/', views.DetailActorView.as_view(), name='detail_actor'),
    path('UpdateActorView/<int:pk>/', views.UpdateActorView.as_view(), name='update_actor'),
    path('DeleteActorView/<int:pk>/', views.DeleteActorView.as_view(), name='delete_actor'),
]

accounts/models.py
from django.db import models


# Create your models here.
class Actor(models.Model):
    nn = models.CharField(max_length=123)

movie/models.py
from django.db import models


# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"{self.title} {self.year}"


class Actor(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    def clean(self):
        data = super().clean()
        self.user = authenticate(**data)
        if self.user is None:
            raise ValidationError("nie poprawne dane logowania")
        return data


class SingUpForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    re_password = forms.CharField(max_length=50, widget=forms.PasswordInput, label='Re-password')

    def clean(self):
        data = super().clean()
        if data.get('password') != data.get('re_password'):
            raise ValidationError('Hasła się nie zgadzają!!!')
        return data

movie/forms.py
from django import forms

from movie.models import Movie


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from accounts.forms import LoginForm, SingUpForm


class LoginView(View):
    def get(self, request):

        form = LoginForm()
        return render(request, 'form.html', {'form': form})

    def post(self, request):
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            login(request, loginForm.user)
            return redirect("/")
        return render(request, 'form.html', {'form': loginForm})


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('/')


class SignUpView(View):

    def get(self, request):
        form = SingUpForm()
        return render(request, 'form.html', {'form': form})

    def post(self, request):
        form = SingUpForm(request.POST)
        if form.is_valid():
            del form.cleaned_data['re_password']
            User.objects.create_user(**form.cleaned_data)
            return redirect("/")
        return render(request, 'form.html', {'form': form})

movie/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView

from movie.forms import MovieForm
from movie.models import Movie, Actor
from django.contrib.auth.models import User


class AddMovieView(LoginRequiredMixin, View):

    def get(self, request):
        form = MovieForm()
        return render(request, 'form.html', {'form': form})

    def post(self, request):
        form = MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list_movie')
        return render(request, 'form.html', {'form': form})


class ListMovieView(View):

    def get(self, request):
        movies = Movie.objects.all()
        return render(request, 'list.html', {'object_list': movies})


class AddActorView(PermissionRequiredMixin, CreateView):
    permission_required = ['movie.add_actor']
    model = Actor
    fields = '__all__'
    template_name = 'form.html'

    def get_success_url(self):
        actor = self.object
        url = reverse('detail_actor', args=(actor.id,))
        return url


class DetailActorView(DetailView):
    model = Actor
    template_name = 'detailActor.html'


class UpdateActorView(UserPassesTestMixin, UpdateView):
    model = Actor
    fields = '__all__'
    template_name = 'form.html'

    def get_success_url(self):
        actor = self.object
        url = reverse('detail_actor', args=(actor.id,))
        return url

    def test_func(self):
        return self.request.user.username == 'Gosia'


class DeleteActorView(DeleteView):
    model = Actor
    template_name = 'delete_form.html'
    success_url = reverse_lazy('list_actor')


class ListActorView(ListView):
    model = Actor
    template_name = 'list.html'

templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'bootstrap-5.0.2/css/bootstrap.css' %}" rel="stylesheet">

    <title>Document</title>
</head>
<body>
<div class="container bg-light">
    <div class="row ">
        <div class="col text-center ">
            {% include 'navbar.html' %}

        </div>
    </div>
    <div class="row mt-5 ">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</div>

</body>
</html>

templates/delete_form.html
{% extends 'base.html' %}
{% block content %}
    czy jestes pewien żę chcesz usunąc obiekt {{ object }}.
    <form method="post" class="bg-light">
        {% csrf_token %}
        {{ form.as_p }}
       <input type="submit" value="Confirm">
    </form>
{% endblock %}

templates/detailActor.html
{% extends 'base.html' %}
{% block content %}
    <div class="card p-2">
        <div class="card-body">
            {{ object.first_name }} {{ object.last_name }}
        </div>
    </div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block content %}

    <form method="post" class="bg-light">
        {% csrf_token %}
            {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block content %}

    <h1 class="text-center">Filmy</h1>

    <ul class="list-group">
        {% for item in object_list %}
            <li class="list-group-item m-1"> {{ item }}
            <ul class="list-group list-group-horizontal">
                {% if perms.movie.change_actor %}
                <a class="list-group-item list-group-item-action" href="{% url 'update_actor' item.id %}">Edytuj </a>
                {% endif %}
                <a class="list-group-item list-group-item-action" href="{% url 'detail_actor' item.id %}">Szczegóły </a>
                <a class="list-group-item list-group-item-action" href="{% url 'delete_actor' item.id %}">Usuń </a>
            </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/navbar.html
<ul class="list-group list-group-horizontal">
    <a href="{% url 'add_movie' %}" class="list-group-item list-group-item-action">Dodaj Film</a>
    <a href="{% url 'list_movie' %}" class="list-group-item list-group-item-action">Lista Filmow</a>
    <a href="{% url 'add_actor' %}" class="list-group-item list-group-item-action">Dodaj Aktora</a>
    <a href="{% url 'list_actor' %}" class="list-group-item list-group-item-action">Lista Aktorów</a>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="list-group-item list-group-item-action">Wyloguj</a>
    {% else %}
        <a href="{% url 'login' %}" class="list-group-item list-group-item-action">Zaloguj</a>
        <a href="{% url 'signup' %}" class="list-group-item list-group-item-action">Rejestracja</a>
    {% endif %}
</ul>